### ISSUE TITLE
test failing with: undefined symbol: _ZTI16SpatialException

### ISSUE THREAD

**Issue by captainkirk99** [SpatioTemporal/pystare#30]
I just successfully built and installed pystare.

```
(stare) ed@koko:~$ pip3 install --editable pystare
Obtaining file:///home/ed/pystare
Requirement already satisfied: numpy>=1.16.2 in ./anaconda3/envs/stare/lib/python3.7/site-packages (from pystare==0.6.0) (1.19.2)
Requirement already satisfied: shapely>=1.6 in ./anaconda3/envs/stare/lib/python3.7/site-packages (from pystare==0.6.0) (1.7.1)
Requirement already satisfied: geopandas>=0.5 in ./anaconda3/envs/stare/lib/python3.7/site-packages (from pystare==0.6.0) (0.9.0)
Requirement already satisfied: fiona>=1.8 in ./anaconda3/envs/stare/lib/python3.7/site-packages (from geopandas>=0.5->pystare==0.6.0) (1.8.19)
Requirement already satisfied: pyproj>=2.2.0 in ./anaconda3/envs/stare/lib/python3.7/site-packages (from geopandas>=0.5->pystare==0.6.0) (3.0.1)
Requirement already satisfied: pandas>=0.24.0 in ./anaconda3/envs/stare/lib/python3.7/site-packages (from geopandas>=0.5->pystare==0.6.0) (1.2.4)
Requirement already satisfied: six>=1.7 in ./anaconda3/envs/stare/lib/python3.7/site-packages (from fiona>=1.8->geopandas>=0.5->pystare==0.6.0) (1.15.0)
Requirement already satisfied: click-plugins>=1.0 in ./anaconda3/envs/stare/lib/python3.7/site-packages (from fiona>=1.8->geopandas>=0.5->pystare==0.6.0) (1.1.1)
Requirement already satisfied: cligj>=0.5 in ./anaconda3/envs/stare/lib/python3.7/site-packages (from fiona>=1.8->geopandas>=0.5->pystare==0.6.0) (0.7.1)
Requirement already satisfied: attrs>=17 in ./anaconda3/envs/stare/lib/python3.7/site-packages (from fiona>=1.8->geopandas>=0.5->pystare==0.6.0) (20.3.0)
Requirement already satisfied: click<8,>=4.0 in ./anaconda3/envs/stare/lib/python3.7/site-packages (from fiona>=1.8->geopandas>=0.5->pystare==0.6.0) (7.1.2)
Requirement already satisfied: certifi in ./anaconda3/envs/stare/lib/python3.7/site-packages (from fiona>=1.8->geopandas>=0.5->pystare==0.6.0) (2020.12.5)
Requirement already satisfied: munch in ./anaconda3/envs/stare/lib/python3.7/site-packages (from fiona>=1.8->geopandas>=0.5->pystare==0.6.0) (2.5.0)
Requirement already satisfied: python-dateutil>=2.7.3 in ./anaconda3/envs/stare/lib/python3.7/site-packages (from pandas>=0.24.0->geopandas>=0.5->pystare==0.6.0) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in ./anaconda3/envs/stare/lib/python3.7/site-packages (from pandas>=0.24.0->geopandas>=0.5->pystare==0.6.0) (2021.1)
Installing collected packages: pystare
  Running setup.py develop for pystare
Successfully installed pystare

```

But when I try and run tests, it fails. What am I doing wrong?

```
(stare) ed@koko:~/pystare$ python3 setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing pystare.egg-info/PKG-INFO
writing dependency_links to pystare.egg-info/dependency_links.txt
writing requirements to pystare.egg-info/requires.txt
writing top-level names to pystare.egg-info/top_level.txt
reading manifest file 'pystare.egg-info/SOURCES.txt'
writing manifest file 'pystare.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.7/_pystare.cpython-37m-x86_64-linux-gnu.so -> 
test_srange (unittest.loader._FailedTest) ... ERROR
test_spatial (unittest.loader._FailedTest) ... ERROR
test_temporal (unittest.loader._FailedTest) ... ERROR
test_intersections (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_srange (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_srange
Traceback (most recent call last):
  File "/home/ed/anaconda3/envs/stare/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/ed/pystare/tests/test_srange.py", line 2, in <module>
    import pystare
  File "/home/ed/pystare/pystare.py", line 15, in <module>
    import _pystare
ImportError: /home/ed/pystare/_pystare.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTI16SpatialException



```

**Comment by captainkirk99** [comment]
Similarly, when I try to use pystare in any way, I get a failure with this missing symbol...


```
(stare) ed@koko:~$ python3
Python 3.7.10 (default, Feb 26 2021, 18:47:35) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import pystare
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ed/pystare/pystare.py", line 15, in <module>
    import _pystare
ImportError: /home/ed/pystare/_pystare.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTI16SpatialException
>>> 
```

**Comment by michaelleerilee** [comment]
Were the STARE environment variables set?

**Comment by NiklasPhabian** [comment]
I'd assume this is not relevant anymore with pystare version 0.8 and above
